lgbm:
  n_estimators: 400
  num_leaves: 63
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 7
calibration: isotonic
labels:
  pt_mult: 1.5
  sl_mult: 1.0
  max_h: 20
features:
  list: [rsi14, rv20, mom_5, atr14, vol_norm]
